baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Project'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'

  [[menus.main]]
    name = 'Documentation'
    pageRef = '/documentation'

  [[menus.main]]
    name = 'Publications and Outreach'
    pageRef = '/publications'

  [[menus.main]]
    name = 'Meet the Team'
    pageRef = '/meet-the-team'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
