# Requires the following to be set in your repository:
# Variables:
# - UPLOAD_TARGET: The rsync target string (e.g., user@host:/path)
# Secrets:
# - DEPLOYMENT_KEY_CONTENT: The private SSH key for deployment
name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        run: |
          RESPONSE=$(curl -X POST --url "$LOGIN_TARGET" --header "Content-Type: application/json" --data "{\"grant_type\":\"client_credentials\", \"client_id\":\"$CLIENT_DEPLOY\",  \"client_secret\":\"$CLIENT_SECRET\"}")
          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: publish
        run: 'curl -X POST --url "$UPLOAD_TARGET" --header "Authorization: Bearer $TOKEN"'
    env:
      UPLOAD_TARGET: ${{ vars.UPLOAD_TARGET }}
      LOGIN_TARGET: ${{ vars.LOGIN_TARGET }}
      CLIENT_DEPLOY: ${{ vars.CLIENT_DEPLOY }}
      CLIENT_SECRET: ${{ secrets.API_DEPLOY_ELSI }}
